### ISSUE TITLE
Investigate output limitation overhead

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#1802] opened 2022-11-11 08:22 UTC
For some programs that have **many** flushes (unbuffered output), we did discover a non-trivial overhead in the way we limit the size of the output that teams can write.

We should investigate how high that overhead is and if there is low hanging fruits to reduce it.

**Comment by eldering** [comment] 2023-05-08 13:56
I've looked at this a while ago (after Dhaka), but wasn't able to clearly reproduce this. Also in Dhaka the runtime depended in weird ways on how/where we ran it. From my recollection for example, it made a big difference whether we'd redirect the program output to a file on `/tmp` or elsewhere, even though both FS's were located on the SSD, and this was running outside of DOMjudge.

If I have time, I may try to dive into this one more time.

**Comment by meisterT** [comment] 2023-12-14 19:32
I had some time to look into runguard and runpipe and wrote up a proposal: https://docs.google.com/document/d/1WZRwdvJUamsczYC7CpP3ZIBU8xG6wNqYqrNJf7osxYs/edit?usp=sharing

**Comment by vmcj** [comment] 2024-03-25 17:03
@meisterT @eldering can I close this one? I think we're aware of this issue and can't currently reproduce this.

**Comment by eldering** [comment] 2024-03-26 07:49
I think there was more than just what @meisterT 's proposal is addressing (which is slow flushes in interactive problems), see my comments above. But since I was not able to reproduce this, yes, I think this can be closed until we run into it again.

**Closed** 2024-03-26 10:07 UTC
Labels: unreproducible, judging backend
