### ISSUE TITLE
Port admin/role restrictions to master

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#374] opened 2018-05-28 21:07 UTC
Responding to clarifications requires admin rights, see:
https://github.com/DOMjudge/domjudge/commit/2c5dd8ff3e50723bc96001c31627f769b073acff

Rejudging requires admin permissions, see: https://github.com/DOMjudge/domjudge/commit/2c5dd8ff3e50723bc96001c31627f769b073acff

**Comment by thijskh** [comment] 2018-07-12 14:24
Duplicate of #249. Changes in ICPC-live are not interesting enough to salvage them in current form.

**Closed by thijskh** 2018-07-12 14:24 UTC
