### ISSUE TITLE
Judgehost is being blocked on submission

### ISSUE THREAD

**Issue by baziorek** [DOMjudge/domjudge#1583] opened 2022-05-19 04:40 UTC
NOTE: If this is a _discussion starter_, you need any _installation help_ or have a _question_ on how to accomplish something,
rather post at [our discussion channel](https://www.domjudge.org/chat) or send an email to our
[DOMjudge-devel mailinglist](https://www.domjudge.org/mailman/postorius/lists/domjudge-devel.domjudge.org/)
instead of filing an issue here.

### Description of the problem
I have noticed that one submission is blocking entire DOMjudge - judgehost is keep judging the same submission without any information like in the picture:
![obraz](https://user-images.githubusercontent.com/15332594/169205598-01db28ff-008b-4dab-a627-facfce7f38bb.png)
rest of submissions are queued permanently.

I've checked the submission - it is creating infinite output of empty lines, so it should be timeout or memory limit but there is not.
- Here is submission:
[problematicSubmission.zip](https://github.com/DOMjudge/domjudge/files/8723904/problematicSubmission.zip)
- Problem (description is not in English):
[p15.zip](https://github.com/DOMjudge/domjudge/files/8723907/p15.zip)

### Your environment
- DOMjudge version 7.3.4
- Operating system / Linux distribution and version: Fedora
- nginx for DomServer, Docker for Domjudge

### Steps to reproduce
- Submit of the attached submission for attached problem (but I think that attaching anything for any problem which would create infinite output of empty lines)

### Expected behaviour
Timeout/Output-limit

### Actual behaviour
Infinite JUDGING

### Any other information that you want to share?
(described above)
_______________
EDIT: When I pressed "cancel rejudging on the solution":
![obraz](https://user-images.githubusercontent.com/15332594/169209547-7a3e6254-d1f5-4352-8f29-bdb4b986ee92.png)

**Comment by baziorek** [comment] 2022-05-21 21:14
I was asked to attach files from judgehost from: `judgehost-0:/opt/domjudge/judgehost/judgings/judgedaemon-0-0/endpoint-default/15/6555`
[6555.zip](https://github.com/DOMjudge/domjudge/files/8748350/6555.zip)

**Comment by eldering** [comment] 2022-05-21 21:22
Can you also give the global configuration settings for memory limit and output limit? These can be found under http://example.com/domjudge/jury/config#Judging

**Comment by eldering** [comment] 2022-05-21 21:26
Ah, and the relevant piece of log from the judgehost would also be helpful. You should be able to find the relevant part by searching for the string `6555/121940`.

**Comment by baziorek** [comment] 2022-05-21 21:27
> Can you also give the global configuration settings for memory limit and output limit? These can be found under http://example.com/domjudge/jury/config#Judging

![obraz](https://user-images.githubusercontent.com/15332594/169669524-01b6c41f-d5ed-4eaf-a072-a9d7aa049719.png)

**Comment by baziorek** [comment] 2022-05-21 21:30
> Ah, and the relevant piece of log from the judgehost would also be helpful. You should be able to find the relevant part by searching for the string 6555/121940.
```
[May 21 23:00:27.395] judgedaemon[36]: Working directory: /opt/domjudge/judgehost/judgings/judgedaemon-0-0/endpoint-default/15/6555/121940
[May 21 23:00:29.564] judgedaemon[36]: executing chroot script: 'chroot-startstop.sh start'
cp: '/opt/domjudge/judgehost/judgings/judgedaemon-0-0/endpoint-default/testcase/testcase.15.1.bf9252a416af36c8eb36837502373914.in' and '/opt/domjudge/judgehost/judgings/judgedaemon-0-0/endpoint-default/15/6555/121940/testcase001/testdata.in' are the same file
[May 21 23:00:53.634] testcase_run.sh[4817]: unexpected error, aborting!
[May 21 23:00:53.638] judgedaemon[36]: error: Unknown exitcode from testcase_run.sh for s6555, testcase 1: 127
[..] Setting timezone

Current default time zone: 'Europe/Warsaw'
Local time is now:      Sat May 21 23:00:54 CEST 2022.
Universal Time is now:  Sat May 21 21:00:54 UTC 2022.
```
And many times "aborting"

**Comment by baziorek** [comment] 2022-05-30 01:06
I'm copying questions and answers from slack, to make sure it won't disappear:    
![obraz](https://user-images.githubusercontent.com/15332594/170899941-1f81ddda-225d-48eb-8215-d34e7123b305.png)

**Comment by eldering** [comment] 2022-06-14 21:54
That system check only looks at the size of testdata in/output data, but I think in your case the amount of program output might be the problem. So making sure that the mysql `max_allowed_packet` is larger than (say at least twice as large) the output limit, may solve part of the problem. I think the `cp` error happens because your system got in a weird state. I don't know how to reproduce that.

**Comment by eldering** [comment] 2022-07-23 14:39
Since further problems are not reproducible, I will close the issue with this improvement of the configuration check of `max_allowed_packet`.

**Closed by eldering** 2022-07-23 14:39 UTC
Labels: judging backend
