### ISSUE TITLE
Investigate hanging judgings

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [DOMjudge/domjudge#1307] opened 2021-10-30 17:37 UTC

**Comment by nickygerritsen** [comment] 2021-10-31 11:38
Info: during BAPC we had at least one (maybe more but I left early so not sure) judgings that didn't fully finish. Upon investigation it turned out the `queuetask` table did not have a task anymore for the judging. After reinserting one, it continued. So it seems we clear the table too soon sometimes.

**Comment by meisterT** [comment] 2021-10-31 11:45
Just to clarify: they started but were not completed until a final result was known?

Was there an internal error (perhaps unrelated) around the time?

**Comment by nickygerritsen** [comment] 2021-10-31 11:59
There was no internal error. For the case I saw we missed 5 runs

**Comment by eldering** [comment] 2021-10-31 12:07
I think there were 4 (+/-1) such cases during the contest. There would be a block of 5 testcases that were left unjudged and didn't get picked up. A rejudging didn't have any effect. When checking there were no rows in the `queuetask` table for this judging. It was fixed by manually inserting into that table: then they got picked up and the judging finished without further manual intervention. I'll try and see if I can recoved them.

**Comment by meisterT** [comment] 2021-11-02 08:25
What we see in the access log are for all affected cases lines like this:
```
10.252.19.5 - judgehost [30/Oct/2021:16:14:24 +0200] "POST /api/judgehosts/fetch-work HTTP/2.0" 499 0 "-" "DOMjudge/8.0.0DEV"                                               
```

Always with the same IP address and HTTP status code `499`.

I am speculating that the judgehost claimed this work, the next judgehost deleted the queuetask since all judgetasks are claimed and then because of the `499` the work is unclaimed again. I don't know why there would be such an inconsistency, I would have expected the database change to stick.

Nicky confirmed that there were IP conflicts with this address which could have caused something like this behavior.

**Comment by vmcj** [comment] 2022-01-26 11:20
As discussed in Slack, the issues were now explained and handled for NWERC21.

**Closed by vmcj** 2022-01-26 11:20 UTC
Labels: bug, judging backend
