### ISSUE TITLE
Allow deletion of problem test case

### ISSUE THREAD

**Issue by bumfo** [DOMjudge/domjudge#457] opened 2018-11-18 12:01 UTC
### Description of the problem / feature request
Allow an admin to delete one or more test cases from a problem

### Your environment
DOMjudge 6.0.2

### Steps to reproduce
Open problem edit
Click test case details/edit
Trying to delete a test case

### Expected behaviour
In problem test case details/edit, there is a button to delete a test case.

### Actual behaviour
In problem test case details/edit, there is no button to delete one or more test cases. 

### Any other information that you want to share?
None

**Comment by meisterT** [comment] 2018-11-18 12:05
This is a duplicate of #189.

**Closed by meisterT** 2018-11-18 12:05 UTC
