### ISSUE TITLE
ERROR 1050 (42S01) at line 12: Table 'auditlog' already exists

### ISSUE THREAD

**Issue by wmacevoy** [DOMjudge/domjudge#178] opened 2015-10-13 03:04 UTC
I dropped the database domjudge before running the command

domserver/bin/dj-setup-database -u root -p "$password" install

And I get the above error but it looks like the tables are made:

show tables;
+-----------------------+
| Tables_in_domjudge    |
+-----------------------+
| auditlog              |
| balloon               |
| clarification         |
| configuration         |
| contest               |
| contestproblem        |
| contestteam           |
| event                 |
| executable            |
| judgehost             |
| judgehost_restriction |
| judging               |
| judging_run           |
| language              |
| problem               |
| rankcache_jury        |
| rankcache_public      |
| rejudging             |
| role                  |
| scorecache_jury       |
| scorecache_public     |
| submission            |
| submission_file       |
| team                  |
| team_affiliation      |
| team_category         |
| team_unread           |
| testcase              |
| user                  |
| userrole              |
+-----------------------+

**Comment by meisterT** [comment] 2015-10-13 04:08
Which domjudge version are you using? 5.0.1? current git HEAD?

**Comment by wmacevoy** [comment] 2015-10-13 04:10
5.0.1 ubuntu 14.04 we used 4.0.3 last year and I am running upgrades (this is a fresh install in /usr/local/domjudge after moving the old folder to a backup location)

**Comment by meisterT** [comment] 2015-10-13 06:27
I cannot reproduce the error with the 5.0.1 tarball. Can you reproduce it (after dropping the database again)?

My assumption is that dropping the domjudge database failed somehow.

**Comment by thijskh** [comment] 2015-12-04 19:10
I'm closing this issue. Let us know if you can provide more information on how to reproduce it.

**Closed by thijskh** 2015-12-04 19:10 UTC
Labels: unreproducible
