### ISSUE TITLE
Option to allow Team Member to see the result from RUN-ERROR or WRONG-ANSWER

### ISSUE THREAD

**Issue by hurryman2212** [DOMjudge/domjudge#2526] opened 2024-05-03 04:32 UTC
When you, as Team Member, have COMPILER-ERROR, you can see the result (Compilation output). However, not for RUN-ERROR or WRONG-ANSWER. This is because of the obvious reason that the participants in a "real" contest should have no feedback over their submission.

However, DOMjudge can be used for other use cases such as university homework grading. In such cases, the administrator may want to allow each Team Member to see the output of RUN-ERROR or WRONG-ANSWER to aid participants for debugging their code. For certain types of problems, the building or running process might not be available on their local systems or the runtime result might be different depending on the system types.

So I issue this feature request for adding option to provide the output results from RUN-ERROR or WRONG-ANSWER cases.

**Comment by meisterT** [comment] 2024-05-03 04:46
I'm a little bit hesitant here and wonder whether we should do this. 

I see your motivation but it will make the code more complex while risking giving away the test data. 

Assume teams see the output of their wrong answers, they can just print the input to get the test data. The compilation stage doesn't have access to any test data yet.

**Comment by hurryman2212** [comment] 2024-05-03 05:11
> I'm a little bit hesitant here and wonder whether we should do this.
> 
> I see your motivation but it will make the code more complex while risking giving away the test data.
> 
> Assume teams see the output of their wrong answers, they can just print the input to get the test data. The compilation stage doesn't have access to any test data yet.

I understand your worry over this and I suggest this as "option".

Regarding the test cases, for such cases with the option enabled, randomizing and feeding test inputs can be done in run scripts (so that the need of collecting internal test cases is eliminated). Also, for such cases where the above option is needed, the testcases could be opened to the participants anyway (the motivation of this option itself is to aid participants to debug their own code).

**Comment by vmcj** [comment] 2024-05-03 05:39
Would you need any secret test cases at all for your usecase?

**Comment by hurryman2212** [comment] 2024-05-03 06:06
> Would you need any secret test cases at all for your usecase?

For me, no, at least so far. For others, I think the above idea (using not the "fixed" test cases within DOMjudge but randomized ones by custom `Run` script) can be used. For me, I have used DOMjudge as the grading system for student's homework code.

**Comment by vmcj** [comment] 2024-05-03 13:51
> > Would you need any secret test cases at all for your usecase?
> 
> For me, no, at least so far. For others, I think the above idea (using not the "fixed" test cases within DOMjudge but randomized ones by custom `Run` script) can be used. For me, I have used DOMjudge as the grading system for student's homework code.

I suspect (so please do try) that if you mark everything as sample you can also show the output on sample data which might already be enough for your usecase.

**Comment by eldering** [comment] 2024-05-04 09:02
> > I'm a little bit hesitant here and wonder whether we should do this.
> > I see your motivation but it will make the code more complex while risking giving away the test data.
> > Assume teams see the output of their wrong answers, they can just print the input to get the test data. The compilation stage doesn't have access to any test data yet.
> 
> I understand your worry over this and I suggest this as "option".

The issue is that even an optional feature requires code changes and adds complexity, because we have to consider all the possible ways how optional features might affect each other. Especially optional features that we don't use/test often ourselves could easily break or hide security leaks.

> Regarding the test cases, for such cases with the option enabled, randomizing and feeding test inputs can be done in run scripts (so that the need of collecting internal test cases is eliminated). Also, for such cases where the above option is needed, the testcases could be opened to the participants anyway (the motivation of this option itself is to aid participants to debug their own code).

I think this would only needlessly complicate things. My inclination like @meisterT is also to not do this. But feel free to give it a shot implementing it yourself. If you can make a clean and relatively simple implementation, we could reconsider.

**Comment by hurryman2212** [comment] 2024-05-07 04:14
> > > Would you need any secret test cases at all for your usecase?
> > 
> > 
> > For me, no, at least so far. For others, I think the above idea (using not the "fixed" test cases within DOMjudge but randomized ones by custom `Run` script) can be used. For me, I have used DOMjudge as the grading system for student's homework code.
> 
> I suspect (so please do try) that if you mark everything as sample you can also show the output on sample data which might already be enough for your usecase.

This is actually the method we are currently taking, but like I mentioned in the above, some of the "problem" requires specialized environment or "runner" binary for generating result so not all of the students can run locally and have matching behavior.

After posting this issue, I did a workaround by using CI to problem repo. for all of the student's environment to build and test the test cases so that the above issue can be mediated without touching DOMjudge, by distributing each platform "runner" to the students. Still, thank you for all of your advice.

**Comment by vmcj** [comment] 2024-05-07 05:40
> > > > Would you need any secret test cases at all for your usecase?
> > > 
> > > 
> > > For me, no, at least so far. For others, I think the above idea (using not the "fixed" test cases within DOMjudge but randomized ones by custom `Run` script) can be used. For me, I have used DOMjudge as the grading system for student's homework code.
> > 
> > 
> > I suspect (so please do try) that if you mark everything as sample you can also show the output on sample data which might already be enough for your usecase.
> 
> This is actually the method we are currently taking, but like I mentioned in the above, some of the "problem" requires specialized environment or "runner" binary for generating result so not all of the students can run locally and have matching behavior.
> 
> After posting this issue, I did a workaround by using CI to problem repo. to build and test the test cases for all of the student's environment so that the above issue can be mediated without touching DOMjudge, by distributing each platform "runner" to the students. Still, thank you for all of your advice.

I'll close this but I'm not sure if you understood what I meant:

If you visit the config page [here](https://www.domjudge.org/demoweb/jury/config) there is the option: `Show sample output:` which shows you what happened on the judgehost.

But your solution does work and I don't think we will want to incorporate any code changes (at this point) to facilitate this specific usecase.

**Closed by vmcj** 2024-05-07 05:40 UTC
Labels: enhancement

**Comment by hurryman2212** [comment] 2024-05-07 11:19
> Show sample output

Ah, now I understand what you mean. I just thought you are mentioning the Sample testcase feature itself, which is what I was using to share the test cases with the students. I will try the feature as I think the description of this feature matches very much the thing I want.

**Comment by hurryman2212** [comment] 2024-05-08 05:21
> > Show sample output
> 
> Ah, now I understand what you mean. I just thought you are mentioning the Sample testcase feature itself, which is what I was using to share the test cases with the students. I will try the feature as I think the description of this feature matches very much the thing I want.

Indeed, with `Show sample output: Yes` and `Lazy eval results: Full judging` plus marking all test cases as "sample", I was able to achieve basically what I have requested for. Thank you!
