### ISSUE TITLE
queued/judging submissions in rejudgings

### ISSUE THREAD

**Issue by meisterT** [DOMjudge/domjudge#211] opened 2016-05-18 07:28 UTC
Either queued or currently judged submissions show up as separate row in matrix without title. Add title.

**Comment by eldering** [comment] 2016-05-18 07:47
Why not simply drop them from the matrix?

These are temporary states; I'd prefer to only display submissions that have a final judgement.

**Comment by eldering** [comment] 2016-05-29 05:04
I couldn't reproduce this on my machine wit the 2016 WF dataset, neither with lazy_eval on/off. Looking at the code, it seems that queued or currently judging submisions are not taken into account, only judgings with endtime set.

Did we see this on blue and/or green? Also, we saw so regularly that it doesn't seem to be a race condition.

**Comment by eldering** [comment] 2017-04-24 00:05
I'm closing this as I haven't been able to reproduce it in many rejudgings.

**Closed by eldering** 2017-04-24 00:05 UTC
Labels: unreproducible
