### ISSUE TITLE
The color picker will remove the leading "#" causing color display problem

### ISSUE THREAD

**Issue by kennhung** [DOMjudge/domjudge#1388] opened 2021-12-11 04:56 UTC
NOTE: If this is a _discussion starter_, you need any _installation help_ or have a _question_ on how to accomplish something,
rather post at [our discussion channel](https://www.domjudge.org/chat) or send an email to our
[DOMjudge-devel mailinglist](https://www.domjudge.org/mailman/listinfo/domjudge-devel)
instead of filing an issue here.

### Description of the problem
> The color picker of contest problem and team category will remove the leading "#" from the color code string, and this will cause problem while displaying the color.

### Your environment
> Include details about your installation here.
> - DOMjudge version 7.3.4 (docker image)
> - Debian 10

### Steps to reproduce
> Replace this with a description how we can reproduce your bug.
> - Create a problem and add it to contest.

### Expected behaviour
> After I added the color to the problem, it should show up on the problem list of a contest.

### Actual behaviour
> The color will always showing white whether which color I choose for the problem.

### Any other information that you want to share?
> I go into the database, and I found that the color code string without the leading "#" will have this problem. After I manually added the "#" in front of the color string, the color will show.

**Comment by thijskh** [comment] 2021-12-11 12:36
I cannot reproduce this on 7.3.4 myself I'm afraid. The "#" is always correctly added in Firefox and Chrome. It is also the default behaviour of jscolor to add it. So I would need more info on how to reproduce.

**Comment by thijskh** [comment] 2022-01-26 11:00
Anything you can provide to reproduce this?

**Comment by kennhung** [comment] 2022-01-29 16:30
I'm running DOMserver with the docker image `domjudge/domserver:7.3.3`.
Database is MariaDB 10.5.11.
And I'm using Firefox 95.0.2 to browse the web page.

After I choose a color, it will correctly show at the contest edit page. 
![image](https://user-images.githubusercontent.com/15997384/151668859-956e859a-1aef-4773-8f79-6b1b7a3dbe91.png)

But after I save the contest, it'll show white outside at the contest view page.
![image](https://user-images.githubusercontent.com/15997384/151668883-12b280c9-fa06-487b-97bc-c4616e62444e.png)
![image](https://user-images.githubusercontent.com/15997384/151668891-b6b64f38-7512-47bd-8b68-b8cfa5efc5d1.png)

**Comment by nickygerritsen** [comment] 2022-01-30 09:58
I just tried in Firefox on 7.3.4 but for me the colors appear as `#b6ff8c`, i.e. *with* a `#` and also with small letters. Can you show a screenshot of how your color picker popup looks like? I'm wondering whether it is not a problem with loading the javascript, thus having the built in browser color picker.

**Comment by vmcj** [comment] 2022-01-30 12:58
> I'm wondering whether it is not a problem with loading the javascript, thus having the built in browser color picker.

Maybe also show the output of Inspect, righclick->inspect > Console

**Comment by kennhung** [comment] 2022-01-30 15:12
Here's the screenshot of the color picker.
![image](https://user-images.githubusercontent.com/15997384/151705419-fe40a3b8-817d-47e7-9b6b-d01e842ac49e.png)

And there's nothing in the console when I open or select the color.

**Comment by nickygerritsen** [comment] 2022-01-31 07:55
So I think this is because we set the options for jscolor on the class and somehow your browser doesn't accept them. See http://github.com/DOMjudge/domjudge/blob/7.3/webapp/src/Form/Type/ContestProblemType.php#L52-L52 .
But I am not sure why not, seeing it does for me with the latest Firefox.

I also don't know how we can easily fix this.

Note that DOMjudge 8.0 (released yesterday) has a new color picker, which should work.

**Comment by meisterT** [comment] 2022-04-18 10:46
Since the current major version is using a different color picker and we can't repro the problem for 7.4, I am going to close the issue.

**Closed by meisterT** 2022-04-18 10:46 UTC
Labels: needs-input
