### ISSUE TITLE
Cannot add new contest FormRenderer::renderBlock()

### ISSUE THREAD

**Issue by kietnaptit** [DOMjudge/domjudge#2164] opened 2023-09-28 07:14 UTC
NOTE: If this is a _discussion starter_, you need any _installation help_ or have a _question_ on how to accomplish something,
rather post at [our discussion channel](https://www.domjudge.org/chat) or send an email to our
[DOMjudge-devel mailinglist](https://www.domjudge.org/mailman/postorius/lists/domjudge-devel.domjudge.org/)
instead of filing an issue here.

### Description of the problem
> Hello. When I tried to add new contest, First I got problem like #2160, I have tried to replace the file ContestController.php with the file in 1294b6e commit. But now I got this 500 Error

`Symfony\Component\Form\FormRenderer::renderBlock(): Argument #1 ($view) must be of type Symfony\Component\Form\FormView, Symfony\Component\Form\Form given, called in /home/nguyenanhkiet/domjudge/domserver/webapp/var/cache/prod/twig/c2/c27a4bcb507de3cb22321267dda0e838.php on line 40`

### Your environment
> Include details about your installation here.
> - DOMjudge version 8.2
> - Operating system / Linux distribution and version: Ubuntu 22.04
> - Webserver: Apache

### Steps to reproduce
> Replace this with a description how we can reproduce your bug.
> - Step 1: Login into Jury
> - Step 2: Click on Contest
> - Step 3: Click on Add new contest

### Expected behaviour
> Open New Contest form

### Actual behaviour
> 500 Error

### Any other information that you want to share?
> Please include webserver, symfony and judgedaemon log snippets here as appropriate.
> Screenshots may help in case of UI bugs.
[Screenshot](https://i.imgur.com/PGzQwMV.png)

**Comment by vmcj** [comment] 2023-10-29 17:19
We fixed the original issue (https://github.com/DOMjudge/domjudge/issues/2160) and released a new version. I've checked and I can't reproduce your issue. I'll close this for now but if you can reproduce this please update the issue so we can fix this (again).

**Closed by vmcj** 2023-10-29 17:19 UTC
