### ISSUE TITLE
No scoreboard for balloon runners (non-public)

### ISSUE THREAD

**Issue by iMylene** [DOMjudge/domjudge#1289] opened 2021-10-19 11:16 UTC
For a non-public contest, the scoreboard does not show up in the header for at least balloon runners.

**Comment by nickygerritsen** [comment] 2021-10-19 11:40
OK so this raises the question: should balloon runners have access to the jury scoreboard?

**Comment by mvr320** [comment] 2021-10-19 11:43
> OK so this raises the question: should balloon runners have access to the jury scoreboard?

I think there should be 2 roles:
_intrapublic_scoreboard
_jury_scoreboard

and the balloon runner should get all semi-public info which is intrapublic, so not the unfrozen standing during the contest but more information than the outside world gets, similar to teams.

**Comment by nickygerritsen** [comment] 2021-10-19 12:00
Wouldn’t the solution then not just be to make a hidden team for the balloon user?

**Comment by nickygerritsen** [comment] 2021-10-19 12:08
Yeah good question. We could maybe make /jury/scoreboard return the 'public' scoreboard for balloon users. What do others think?

**Comment by nickygerritsen** [comment] 2021-10-19 12:09
For the roles: I don't like adding all these roles...

**Comment by nickygerritsen** [comment] 2021-10-19 12:50
> > For the roles: I don't like adding all these roles...
> 
> I meant an internal role not one in the GUI, so instead of check for ROLE_JURY we check for which scoreboard can actually be accessed, similar to how the ROLE_ADMIN also has ROLE_JURY.

Ah so you actually want the same idea I have? Allow both ballon and jury to view the scoreboard but when you are not jury, only show the 'public' one?

**Comment by nickygerritsen** [comment] 2021-10-19 13:14
That is not what I'm suggesting. What I want to do is in this method: http://github.com/DOMjudge/domjudge/blob/main/webapp/src/Controller/Jury/ScoreboardController.php#L42-L42
set the `$jury` param only to true if you have the `ROLE_JURY`, otherwise set it to false. Then in that same controller change the security to also have balloon in it. That should be all to make balloon users see the 'public' (what you call intrapublic...) scoreboard.

**Comment by eldering** [comment] 2021-10-19 14:23
> That is not what I'm suggesting. What I want to do is in this method: [http://github.com/DOMjudge/domjudge/blob/main/webapp/src/Controller/Jury/ScoreboardController.php#L42-L42](https://github.com/DOMjudge/domjudge/blob/main/webapp/src/Controller/Jury/ScoreboardController.php#L42-L42) set the `$jury` param only to true if you have the `ROLE_JURY`, otherwise set it to false. Then in that same controller change the security to also have balloon in it. That should be all to make balloon users see the 'public' (what you call intrapublic...) scoreboard.

I think that makes it confusing whether you're looking at the real jury scoreboard, or the public scoreboard within the jury interface, both in the UI and in the jury controller code. I think it would be cleaner to instead if you're in the jury interface and don't have the right to view the jury scoreboard (as in this case balloon runners), we show a link in the menu to the public scoreboard (just like we show a link to the team UI if you're a jury member with a team associated to it).

**Comment by nickygerritsen** [comment] 2021-10-19 14:26
> > That is not what I'm suggesting. What I want to do is in this method: [http://github.com/DOMjudge/domjudge/blob/main/webapp/src/Controller/Jury/ScoreboardController.php#L42-L42](https://github.com/DOMjudge/domjudge/blob/main/webapp/src/Controller/Jury/ScoreboardController.php#L42-L42) set the `$jury` param only to true if you have the `ROLE_JURY`, otherwise set it to false. Then in that same controller change the security to also have balloon in it. That should be all to make balloon users see the 'public' (what you call intrapublic...) scoreboard.
> 
> I think that makes it confusing whether you're looking at the real jury scoreboard, or the public scoreboard within the jury interface, both in the UI and in the jury controller code. I think it would be cleaner to instead if you're in the jury interface and don't have the right to view the jury scoreboard (as in this case balloon runners), we show a link in the menu to the public scoreboard (just like we show a link to the team UI if you're a jury member with a team associated to it).

The problem is/was if you make the contest *non public*. Then there IS no public scoreboard. Or are you suggesting that we *do* allow that for balloon users? That could also work.

**Comment by nickygerritsen** [comment] 2021-11-23 22:35
What is the actual usecase for seeing the scoreboard as a balloon runner? Just wondering.

**Comment by iMylene** [comment] 2021-11-24 07:38
> What is the actual usecase for seeing the scoreboard as a balloon runner? Just wondering.

In practice, the runners like to see the main scoreboard for fun to see how their favorite team is doing overall. 

So we do a split-screen in the balloon room with the balloon handout interface and the scoreboard.

**Comment by nickygerritsen** [comment] 2021-11-24 07:49
Depending on how we do it (the clean way or the fast way) this is non trivial. I wonder if 'for fun' is a good argument, but I'm also not opposed to the idea.

**Comment by vmcj** [comment] 2022-10-09 16:45
So I was looking at what should be moved outside and depending on how you use the system there are some more features which should probably be moved outside:
- Clarifications
- Print

So the question is, should there be a `/staff` which can link to jury only features (80% of what lives under `/jury`)

For now I think the easiest way to close this issue is to make /staff/scoreboard which basically is a copy of /jury/scoreboard but has a warning on that this is "public" instead of unthawed information.

**Closed** 2023-05-06 13:47 UTC
Labels: enhancement, web interface, needs-input
