### ISSUE TITLE
In the contestant's clarifications block, the shortname and color of the problem are not displayed correctly.

### ISSUE THREAD

**Issue by Dup4** [DOMjudge/domjudge#2279] opened 2023-12-13 13:49 UTC
NOTE: If this is a _discussion starter_, you need any _installation help_ or have a _question_ on how to accomplish something,
rather post at [our discussion channel](https://www.domjudge.org/chat) or send an email to our
[DOMjudge-devel mailinglist](https://www.domjudge.org/mailman/postorius/lists/domjudge-devel.domjudge.org/)
instead of filing an issue here.

### Description of the problem

<img width="1109" alt="image" src="https://github.com/DOMjudge/domjudge/assets/38343778/bcec4acf-3e36-431b-b8bc-2237d5b8db9a">

This is the problem I set in the contest, with the correct shortname and color set.

<img width="1690" alt="image" src="https://github.com/DOMjudge/domjudge/assets/38343778/035c14af-d810-4a03-9560-5c6e0c72fce5">

This is the Clarifications page in the administrator interface, showing the correct shortname and color.

<img width="935" alt="image" src="https://github.com/DOMjudge/domjudge/assets/38343778/ab4c2052-7318-4f73-8042-cc431b193930">

But this is the Clarifications page in the contestant's interface, and it doesn't show the correct shortname and color.

This should be the shortname of the problem.

### Your environment

- DOMjudge: 8.2.2
- OS: Ubuntu22.04
- webserver: nginx

### Steps to reproduce

- create a contest.
- send a clarification in contestant's interface.

### Expected behaviour
> Replace this line with what you would expect to happen.

On the Clarifications page in the contestant's interface, the correct shortname and color are shown.

### Actual behaviour
> Replace this line with what happens instead.

The Clarifications page in the contestant's interface currently shows the externalid of the title and the color black.

### Any other information that you want to share?

<img width="1820" alt="image" src="https://github.com/DOMjudge/domjudge/assets/38343778/059ac4f3-3df2-48f4-af5e-8d415d9b53c2">

My data source options are set like this.

**Comment by nickygerritsen** [comment] 2023-12-13 14:57
I tried reproducing this on 8.2.2, but I can't, even with that data source option. A dump of relevant tables of your database might help.

**Comment by Dup4** [comment] 2023-12-14 00:49
Maybe it's because I have two contests?

<img width="1793" alt="image" src="https://github.com/DOMjudge/domjudge/assets/38343778/a3395d38-dd77-4029-9de6-b1addd3cf970">

TESTOFFICIAL:

<img width="1246" alt="image" src="https://github.com/DOMjudge/domjudge/assets/38343778/f2e78e49-42e3-42c9-a39f-cd089936ff87">

Hangzhou_Onsite:

<img width="1241" alt="image" src="https://github.com/DOMjudge/domjudge/assets/38343778/7991d8d0-951d-4cf5-b711-d6407a3549db">

I didn't set the correct shortname in the first contest(TESTOFFICIAL).

But our official contest is in the second contest(Hangzhou_Onsite).

**Comment by vmcj** [comment] 2023-12-14 07:44
> Maybe it's because I have two contests?
> <img alt="image" width="1793" src="https://private-user-images.githubusercontent.com/38343778/290365847-a3395d38-dd77-4029-9de6-b1addd3cf970.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1Mzk1MDksIm5iZiI6MTcwMjUzOTIwOSwicGF0aCI6Ii8zODM0Mzc3OC8yOTAzNjU4NDctYTMzOTVkMzgtZGQ3Ny00MDI5LTlkZTYtYjFhZGRkM2NmOTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA3MzMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMTllNmZmMjM4YTU3YjMyY2Q0ODVmMWUwZGJmOTlmMjkyZWJhNWJiNmNjMjI4MDE5ZGVmZDI5ZTg4YmE5MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CRomz9ixp1K1JuCW4jBBFRzeiqv_BnIW2J8l4lzo7Sk">
> 
> TESTOFFICIAL:
> <img alt="image" width="1246" src="https://private-user-images.githubusercontent.com/38343778/290365871-f2e78e49-42e3-42c9-a39f-cd089936ff87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1Mzk1MDksIm5iZiI6MTcwMjUzOTIwOSwicGF0aCI6Ii8zODM0Mzc3OC8yOTAzNjU4NzEtZjJlNzhlNDktNDJlMy00MmM5LWEzOWYtY2QwODk5MzZmZjg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA3MzMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NjY2MTQ0NGZlNmI1MWQ2OGYzOWNkZWMwNDk4MjZhMWM5YTEwZDA1ZDc0Mzc3YWZhMDVlMzA2NmNjMDc3ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sXzxMg8twcwgVUcTkbmtX7J06WTng8czb8rcPrcc_5g">
> 
> Hangzhou_Onsite:
> <img alt="image" width="1241" src="https://private-user-images.githubusercontent.com/38343778/290365945-7991d8d0-951d-4cf5-b711-d6407a3549db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1Mzk1MDksIm5iZiI6MTcwMjUzOTIwOSwicGF0aCI6Ii8zODM0Mzc3OC8yOTAzNjU5NDUtNzk5MWQ4ZDAtOTUxZC00Y2Y1LWI3MTEtZDY0MDdhMzU0OWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA3MzMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MjI4ZDJhMmU1NjRmNTg3M2M1ZmUwNzI1YTU1MzY3OTU0MzZkZjVkMzVlNTY2ZDQ5ZTdmZTU0MWQzMDZjNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gS3fKUYod_wMmtXrCm5IetCZo_c6C5Bko5iKxqWKp6I">
> 
> I didn't set the correct shortname in the first contest(TESTOFFICIAL).
> 
> But our official contest is in the second contest(Hangzhou_Onsite).

You are aware that the color (and shortname) for a problem is set per contest? So it would really be helpful for us to get a dump so we can easily check what is set.

If I understand you correctly you have the datasource to 1, but expect in the contestant interface that the shortname is shown? We display the externalID by design for this mode as to any outsider (either contestant or a downstream client) we use the externalID, and only internally (for us as admin maybe jury or in the database) we might use the internal identifier.

Also the color in the TESTOFFICIAL is for all problems set to black, that is the same as what we see for the contestant when they are in that contest? Have you set specific colors for that problem already? Are the problems shared over multiple contests?

**Comment by Dup4** [comment] 2023-12-14 13:42
I can provide you with a sql dump, but how do I transfer it to you?

**Comment by nickygerritsen** [comment] 2024-01-12 10:27
> I can provide you with a sql dump, but how do I transfer it to you?

The best option is to send it in a PM in Slack I think.

**Comment by vmcj** [comment] 2024-05-21 15:23
@Dup4 did you send the dump to @nickygerritsen or can we close this issue?

**Comment by 2018hahazhufeng** [comment] 2024-05-23 02:33
The same issue happened to me last week. I can also provide a dump in case it's needed.

**Comment by vmcj** [comment] 2024-05-23 05:51
> The same issue happened to me last week. I can also provide a dump in case it's needed.

That would be helpful, you can send it to one of us on Slack (or share it via pastebin for example).

**Closed** 2024-05-28 20:04 UTC
Labels: unreproducible, web interface
