### ISSUE TITLE
json API

### ISSUE THREAD

**Issue by TPolzer** [DOMjudge/domjudge#202] opened 2016-04-25 10:13 UTC
I tried using the json API (for a live scoreboard), but discovered that it is "interesting":
- Basic Auth works, but breaks clients that expect a 'WWW-Authenticate' header in conformance with rfc1945.
- /api/scoreboard gives no time information for unsolved problems.
- Is my assumtion correct, that "pending" in /api/scoreboard always means "submitted after freeze" (and public scoreboard)?
- /api/submissions lists submissions that are marked as invalid
- The API is not suited to streaming results. Theoretically there is the 'fromid' parameter, but that clashes with submissions that are marked invalid after the fact. Ideally (from a user perspective), I would want access to an event _log_, where nothing can "unhappen" (without an explicit event).

**Comment by thijskh** [comment] 2016-04-25 13:32
For starters, the API is indeed quite rudimentary and is definitely subject to being improved. Your suggestions are therefore very welcome.

1. A bug indeed, can you create a pull request?
1. We implement https://clics.ecs.baylor.edu/index.php/JSON_Scoreboard_2016. What "time" would an unsolved problem display? The ICPC scoring system does not calculate time for unsolved problems, they score 0 until solved.
1. According to the standard, something can be "pending" it's unjudged, unverified when verification is required, or submitted after freeze. DOMjudge currently only implements the latter part, we don't update the scoreboard before the freeze when receiving something we have yet to judge.
1. This is a known bug, but it seems we didn't file it yet. A pull request would also be welcome here.
1. Am I right to conclude that your only problem is with solutions that can be marked invalid? The problem is indeed that marking submissions invalid is supposed to remove them completely from the contest. This is a last-resort measure that only needs to be used in highly exceptional circumstances. I'm not sure it's worth it to create something different just for this?

**Comment by TPolzer** [comment] 2016-04-25 13:44
(2) came from my idea that I could get all the required data (for both jury and public scoreboard display) form polling just the jury scoreboard. Probably not a good idea.
I know that (5) sounds awkward, on the other hand a scoreboard should always display consistent data, even under exceptional circumstances.

**Comment by meisterT** [comment] 2016-04-25 19:41
re 5: this also applies for rejudgings, doesn't it?

General question: do you want to implement your own new scoreboard? Or do you want to try to connect an existing one?

**Comment by TPolzer** [comment] 2016-04-26 04:49
Rejudgings are just judgings for the same submission with a higher id, aren't they?

I want to implement a new scoreboard.I know that there is this standardized "ext.php" interface, but I do not want to poll this potentially several megabytes large file (over WLAN).

**Comment by TPolzer** [comment] 2016-05-14 09:04
After close examination of the API I came to the conclusion that the fromid parameter of /api/judgings is useless (not sure about /api/submissions), since as a client I have no idea what the valid range of ids is, and they are not guaranteed to have monotonic ids.

**Comment by meisterT** [comment] 2016-05-15 06:57
You're totally right. I think you have to add add an (optional) argument to the  api/judgings call to query for a specific judging associated with a submission ID. Pull requests welcome :-)

**Comment by eldering** [comment] 2017-10-22 21:09
We're currently working on implementing the (draft) [Contest API](https://clics.ecs.baylor.edu/index.php/Contest_API). Feedback on that API is welcome!
As we're obsoleting the ext.php XML feed and or old JSON API, I'm closing this issue.

**Closed by eldering** 2017-10-22 21:09 UTC
Labels: API
